# Generated by Django 6.0.4 on 2026-05-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_admission_no_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='term',
        ),
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(choices=[('901', '901 - English Language'), ('902', '902 - Kiswahili'), ('903', '903 - Mathematics'), ('904', '904 - Kenyan Sign Language'), ('905', '905 - Integrated Science'), ('906', '906 - Agriculture and Nutrition'), ('907', '907 - Social Studies'), ('908', '908 - Christian Religious Education (CRE)'), ('909', '909 - Islamic Religious Education (IRE)'), ('910', '910 - Hindu Religious Education (HRE)'), ('911', '911 - Creative Arts and Sports'), ('912', '912 - Pre-Technical Studies')], max_length=3),
        ),
    ]
