# Generated by Django 6.0.4 on 2026-05-04 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_mark_date_recorded_remove_mark_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='performance_level',
            field=models.CharField(default='pending', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='points',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='term',
            field=models.CharField(default='Term 1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student'),
        ),
    ]
