# Generated by Django 6.0.4 on 2026-05-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_mark_date_recorded_mark_performance_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(choices=[('901', 'English Language'), ('902', 'Kiswahili'), ('903', 'Mathematics'), ('904', 'Kenyan Sign Language'), ('905', 'Integrated Science'), ('906', 'Agriculture and Nutrition'), ('907', 'Social Studies'), ('908', 'CRE'), ('909', 'IRE'), ('910', 'HRE'), ('911', 'Creative Arts and Sports'), ('912', 'Pre-Technical Studies')], max_length=3),
        ),
    ]
