# Generated by Django 6.0.4 on 2026-05-05 13:03

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_term_student_year_alter_mark_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='year',
            field=models.IntegerField(default=students.models.current_year),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=students.models.current_year),
        ),
    ]
