# Generated by Django 6.0.4 on 2026-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_assessment_no_student_guardian_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='exam_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
