# Generated by Django 6.0.4 on 2026-05-14 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_mark_exam_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsc_number', models.CharField(max_length=20, unique=True, verbose_name='TSC Number')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('assigned_task', models.CharField(default='Teacher', max_length=150, verbose_name='Assigned Task')),
                ('subjects_taught', models.CharField(help_text='Separate with commas, e.g., Mathematics, Physics', max_length=200, verbose_name='Subjects Taught')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
