# Generated by Django 6.0.4 on 2026-05-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(choices=[('901', 'English Language'), ('902', 'Kiswahili'), ('903', 'Mathematics'), ('904', 'Kenyan Sign Language'), ('905', 'Integrated Science'), ('906', 'Agriculture and Nutrition'), ('907', 'Social Studies'), ('908', 'CRE'), ('909', 'IRE'), ('910', 'HRE'), ('911', 'Creative Arts and Sports'), ('912', 'Pre-Technical Studies')], max_length=3)),
                ('class_name', models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20)),
                ('stream', models.CharField(choices=[('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Main', 'Main')], max_length=20)),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.teacherprofile')),
            ],
            options={
                'unique_together': {('subject_code', 'class_name', 'stream')},
            },
        ),
    ]
