# Generated by Django 6.0.4 on 2026-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_subjectassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the teacher', max_length=150)),
                ('email', models.EmailField(help_text="Teacher's email address (must be unique)", max_length=254, unique=True)),
                ('subject', models.CharField(help_text='Subject taught by the teacher (e.g., Mathematics, English, Science)', max_length=100)),
                ('classes', models.CharField(help_text='Classes taught (e.g., Grade 7 Yellow, Grade 8 Blue, Grade 9 Main)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the teacher is currently active')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='students_te_name_26de34_idx'), models.Index(fields=['email'], name='students_te_email_84676f_idx'), models.Index(fields=['subject'], name='students_te_subject_c7951b_idx')],
            },
        ),
    ]
