# Generated by Django 6.0.4 on 2026-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='Mr.', help_text='Title (Mr., Ms., Mrs., Dr., Prof.)', max_length=10),
        ),
    ]
