# Generated by Django 6.0.4 on 2026-05-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_teacher_phone_number_teacher_tsc_number_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_task',
            field=models.CharField(choices=[('Class Teacher Grade 7 Yellow', 'Class Teacher Grade 7 Yellow'), ('Class Teacher Grade 7 Blue', 'Class Teacher Grade 7 Blue'), ('Class Teacher Grade 8 Main', 'Class Teacher Grade 8 Main'), ('Class Teacher Grade 9 Main', 'Class Teacher Grade 9 Main'), ('Teacher', 'Teacher')], default='Teacher', help_text='The administrative role or class assignment for this teacher', max_length=100),
        ),
    ]
