# Generated by Django 6.0.4 on 2026-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_teacher_assigned_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherMasterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('term', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('exam_type', models.CharField(max_length=50)),
                ('comment_ee1', models.TextField(blank=True, default='An exceptional performance. Maintain this brilliant standard.')),
                ('comment_ee2', models.TextField(blank=True, default='A very good performance. Keep up the high level of effort.')),
                ('comment_me1', models.TextField(blank=True, default='A solid and commendable performance across most subjects.')),
                ('comment_me2', models.TextField(blank=True, default='A fair performance. With more consistency, a better grade is attainable.')),
                ('comment_ae1', models.TextField(blank=True, default='Approaching competence. Increased focus on weak subjects is required.')),
                ('comment_ae2', models.TextField(blank=True, default='Developing competence. Closer monitoring and regular remedial work needed.')),
                ('comment_be1', models.TextField(blank=True, default='Emerging competence. Needs intensive academic intervention and tracking.')),
                ('comment_be2', models.TextField(blank=True, default='Critical support required. Immediate parental and teacher guidance needed.')),
            ],
            options={
                'unique_together': {('year', 'term', 'grade', 'stream', 'exam_type')},
            },
        ),
    ]
