# Generated by Django 6.0.4 on 2026-05-19 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_classteachermastercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='Unique phone number for SMS alerts', max_length=15, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.guardian'),
            preserve_default=False,
        ),
    ]
