# Generated by Django 6.0.4 on 2026-05-20 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_schoolclient_schooldomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.teacher'),
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_name_26de34_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_subject_c7951b_idx',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects_taught',
            field=models.CharField(default='', help_text='Subjects taught (e.g., Mathematics, Physics). Separate with commas for multiple subjects.', max_length=200, verbose_name='Subjects Taught'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_task',
            field=models.CharField(choices=[('Class Teacher Grade 7 Yellow', 'Class Teacher Grade 7 Yellow'), ('Class Teacher Grade 7 Blue', 'Class Teacher Grade 7 Blue'), ('Class Teacher Grade 8 Main', 'Class Teacher Grade 8 Main'), ('Class Teacher Grade 9 Main', 'Class Teacher Grade 9 Main'), ('Teacher', 'Teacher')], default='Teacher', help_text='Administrative role or class assignment', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='', help_text='Contact phone number', max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tsc_number',
            field=models.CharField(default='', help_text='Teacher Service Commission registration number', max_length=20, unique=True, verbose_name='TSC Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=1, help_text='Link this teacher to their user account for login', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['tsc_number'], name='students_te_tsc_num_a702d6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['subjects_taught'], name='students_te_subject_f18e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_active'], name='students_te_is_acti_47a695_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_user_teacher'),
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
