# Generated by Django 6.0.4 on 2026-05-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_remove_teacherprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclient',
            name='address',
            field=models.CharField(blank=True, help_text='e.g., P.O. BOX 31-80402, Lungalunga', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolclient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolclient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
