# Generated by Django 6.0.4 on 2026-05-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_schoolclient_address_schoolclient_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclient',
            options={'verbose_name': 'Subscribed School', 'verbose_name_plural': 'Subscribed Schools'},
        ),
        migrations.AddField(
            model_name='schoolclient',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='Official School Logo'),
        ),
        migrations.AddField(
            model_name='schoolclient',
            name='status',
            field=models.CharField(choices=[('active', 'Active Subscribed'), ('trial', 'Free Trial Period'), ('suspended', 'Account Suspended (Unpaid)')], default='trial', max_length=20, verbose_name='Account Status'),
        ),
        migrations.AddField(
            model_name='schoolclient',
            name='tier',
            field=models.CharField(choices=[('Basic', 'Basic Exam Entry'), ('Premium', 'Premium + SMS Reports'), ('Enterprise', 'Full System Suite')], default='Basic', max_length=20, verbose_name='Subscription Tier'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='address',
            field=models.CharField(blank=True, help_text='e.g., P.O. BOX 31-80402', max_length=255, null=True, verbose_name='Postal Address'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Billing/Contact Email'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='on_trial',
            field=models.BooleanField(default=True, verbose_name='Is on Trial'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Valid Until'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Official Phone'),
        ),
    ]
