# Generated by Django 6.0.4 on 2026-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_schoolclient_options_schoolclient_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20)),
                ('exam_type', models.CharField(choices=[('Opener Assessment', 'Opener Assessment'), ('Mid Term Assessment', 'Mid Term Assessment'), ('End Term Assessment', 'End Term Assessment')], max_length=50)),
                ('grade', models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20)),
                ('is_locked', models.BooleanField(default=False, help_text='If checked, teachers cannot alter marks for this setting')),
            ],
            options={
                'unique_together': {('year', 'term', 'exam_type', 'grade')},
            },
        ),
    ]
