# Generated by Django 6.0.4 on 2026-05-30 14:32

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_assessmentlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Opener Assessment', 'Opener Assessment'), ('Mid Term Assessment', 'Mid Term Assessment'), ('End Term Assessment', 'End Term Assessment')], max_length=50)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20)),
                ('year', models.IntegerField(default=students.models.current_year)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'term', 'name'],
                'unique_together': {('name', 'term', 'year')},
            },
        ),
    ]
