# Generated by Django 6.0.4 on 2026-05-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='maximum_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mark',
            name='raw_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
