# Generated by Django 6.0.4 on 2026-05-31 09:47

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_mark_maximum_marks_mark_raw_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MarkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(choices=[('901', 'English Language'), ('902', 'Kiswahili'), ('903', 'Mathematics'), ('904', 'Kenyan Sign Language'), ('905', 'Integrated Science'), ('906', 'Agriculture and Nutrition'), ('907', 'Social Studies'), ('908', 'CRE'), ('909', 'IRE'), ('910', 'HRE'), ('911', 'Creative Arts and Sports'), ('912', 'Pre-Technical Studies')], max_length=3)),
                ('class_name', models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20)),
                ('stream', models.CharField(choices=[('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Main', 'Main')], max_length=20)),
                ('exam_name', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20)),
                ('year', models.IntegerField(default=students.models.current_year)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_submissions', to='students.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject_code', 'class_name', 'stream', 'exam_name', 'term', 'year')},
            },
        ),
    ]
