# Generated by Django 6.0.4 on 2026-05-31 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_mark_is_absent_marksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksubmission',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('returned', 'Returned to Teacher'), ('approved', 'Approved'), ('published', 'Published')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='marksubmission',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marksubmission',
            name='exam_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marksubmission',
            name='stream',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marksubmission',
            name='subject_code',
            field=models.CharField(choices=[('901', 'English Language'), ('902', 'Kiswahili'), ('903', 'Mathematics'), ('904', 'Kenyan Sign Language'), ('905', 'Integrated Science'), ('906', 'Agriculture and Nutrition'), ('907', 'Social Studies'), ('908', 'CRE'), ('909', 'IRE'), ('910', 'HRE'), ('911', 'Creative Arts and Sports'), ('912', 'Pre-Technical Studies')], max_length=10),
        ),
        migrations.AlterField(
            model_name='marksubmission',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher'),
        ),
        migrations.AlterField(
            model_name='marksubmission',
            name='term',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='marksubmission',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
