# Generated by Django 6.0.4 on 2026-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_report_card_configuration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('CRE', 'CRE'), ('IRE', 'IRE'), ('None', 'None')], default='None', max_length=10, null=True, verbose_name='Religious Education'),
        ),
    ]
