# Generated by Django 6.0.4 on 2026-06-05 04:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('students', '0029_student_religion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Label')),
                ('grade', models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20)),
                ('stream', models.CharField(choices=[('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Main', 'Main')], max_length=20)),
                ('academic_year', models.IntegerField(default=students.models.current_year)),
                ('class_teacher_name', models.CharField(blank=True, help_text='Display name of the assigned class teacher.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class Room',
                'verbose_name_plural': 'Class Rooms',
                'ordering': ['grade', 'stream'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (Platform Owner)'), ('SCHOOL_ADMIN', 'School Admin'), ('TEACHER', 'Teacher')], default='TEACHER', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('tenant_schema', models.CharField(blank=True, help_text='Postgres schema name of the school this user belongs to. Leave blank for platform-level (SuperAdmin) users.', max_length=63, null=True)),
            ],
            options={
                'verbose_name': 'Platform User',
                'verbose_name_plural': 'Platform Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_admin', models.BooleanField(default=False, help_text='Designates this user as the principal admin contact for the school.')),
                ('joined_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'School Staff Profile',
                'verbose_name_plural': 'School Staff Profiles',
            },
        ),
        migrations.CreateModel(
            name='SystemBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('admins', 'School Admins Only'), ('teachers', 'Teachers Only')], default='all', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Broadcast',
                'verbose_name_plural': 'System Broadcasts',
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=150)),
                ('tsc_number', models.CharField(blank=True, max_length=20)),
                ('class_name', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=20)),
                ('subject_code', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=students.models.current_year)),
                ('exam_type', models.CharField(max_length=50)),
                ('mean_score', models.FloatField(default=0.0, help_text='Class mean for this subject')),
                ('subjects_handled', models.IntegerField(default=1, help_text='Distinct subjects taught this term')),
                ('login_count', models.IntegerField(default=0, help_text='Number of admin logins this month')),
                ('marks_submitted', models.IntegerField(default=0, help_text='Total Mark records entered')),
                ('pass_rate', models.FloatField(default=0.0, help_text='Percentage of students achieving ME2 (≥41) or above')),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher Performance Summary',
                'verbose_name_plural': 'Teacher Performance Summaries',
                'ordering': ['-mean_score'],
            },
        ),
        migrations.AlterModelOptions(
            name='schoolclient',
            options={'verbose_name': 'School (Tenant)', 'verbose_name_plural': 'Schools (Tenants)'},
        ),
        migrations.AlterModelOptions(
            name='schooldomain',
            options={'verbose_name': 'School Domain', 'verbose_name_plural': 'School Domains'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveConstraint(
            model_name='teacher',
            name='unique_user_teacher',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_email_84676f_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_tsc_num_a702d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_subject_f18e5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_is_acti_47a695_idx',
        ),
        migrations.AlterField(
            model_name='assessmentlock',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Billing Email'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Valid Until'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Free Trial'), ('suspended', 'Suspended (Unpaid)')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='tier',
            field=models.CharField(choices=[('Basic', 'Basic — Exam Entry Only'), ('Premium', 'Premium — Exam + SMS Reports'), ('Enterprise', 'Enterprise — Full System Suite')], default='Basic', max_length=20, verbose_name='Subscription Tier'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_task',
            field=models.CharField(choices=[('Class Teacher Grade 7 Yellow', 'Class Teacher Grade 7 Yellow'), ('Class Teacher Grade 7 Blue', 'Class Teacher Grade 7 Blue'), ('Class Teacher Grade 8 Main', 'Class Teacher Grade 8 Main'), ('Class Teacher Grade 9 Main', 'Class Teacher Grade 9 Main'), ('Teacher', 'Teacher')], default='Teacher', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='Mr.', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tsc_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade', 'stream', 'academic_year')},
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='students.schoolclient'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to='students.customuser'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherperformancesummary',
            unique_together={('tsc_number', 'subject_code', 'class_name', 'stream', 'term', 'year', 'exam_type')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolprofile',
            unique_together={('user', 'school')},
        ),
    ]
