# Generated by Django 6.0.4 on 2026-06-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_classroom_customuser_schoolprofile_systembroadcast_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AlterUniqueTogether(
            name='schoolprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='school',
        ),
        migrations.DeleteModel(
            name='TeacherPerformanceSummary',
        ),
        migrations.AlterModelOptions(
            name='schoolclient',
            options={'verbose_name': 'Subscribed School', 'verbose_name_plural': 'Subscribed Schools'},
        ),
        migrations.AlterModelOptions(
            name='schooldomain',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='assessmentlock',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If checked, teachers cannot alter marks for this setting'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=models.CharField(help_text='Unique phone number for SMS alerts', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='address',
            field=models.CharField(blank=True, help_text='e.g., P.O. BOX 31-80402', max_length=255, null=True, verbose_name='Postal Address'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Billing/Contact Email'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='Official School Logo'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='on_trial',
            field=models.BooleanField(default=True, verbose_name='Is on Trial'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Valid Until'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Official Phone'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='status',
            field=models.CharField(choices=[('active', 'Active Subscribed'), ('trial', 'Free Trial Period'), ('suspended', 'Account Suspended (Unpaid)')], default='trial', max_length=20, verbose_name='Account Status'),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='tier',
            field=models.CharField(choices=[('Basic', 'Basic Exam Entry'), ('Premium', 'Premium + SMS Reports'), ('Enterprise', 'Full System Suite')], default='Basic', max_length=20, verbose_name='Subscription Tier'),
        ),
        migrations.AlterField(
            model_name='systembroadcast',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this to instantly pull the alert off all school screens.'),
        ),
        migrations.AlterField(
            model_name='systembroadcast',
            name='message',
            field=models.TextField(verbose_name='Notification Details'),
        ),
        migrations.AlterField(
            model_name='systembroadcast',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users (Everyone)'), ('admins', 'School Admins Only'), ('teachers', 'Teachers Only')], default='all', max_length=15),
        ),
        migrations.AlterField(
            model_name='systembroadcast',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Broadcast Headline'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_task',
            field=models.CharField(choices=[('Class Teacher Grade 7 Yellow', 'Class Teacher Grade 7 Yellow'), ('Class Teacher Grade 7 Blue', 'Class Teacher Grade 7 Blue'), ('Class Teacher Grade 8 Main', 'Class Teacher Grade 8 Main'), ('Class Teacher Grade 9 Main', 'Class Teacher Grade 9 Main'), ('Teacher', 'Teacher')], default='Teacher', help_text='Administrative role or class assignment', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.CharField(help_text='Classes taught (e.g., Grade 7 Yellow, Grade 8 Blue, Grade 9 Main)', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(help_text="Teacher's email address (must be unique)", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the teacher is currently active'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.CharField(help_text='Subjects taught (e.g., Mathematics, Physics). Separate with commas for multiple subjects.', max_length=200, verbose_name='Subjects Taught'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='Mr.', help_text='Title (Mr., Ms., Mrs., Dr., Prof.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tsc_number',
            field=models.CharField(help_text='Teacher Service Commission registration number', max_length=20, unique=True, verbose_name='TSC Number'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(help_text='Link this teacher to their user account for login', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['tsc_number'], name='students_te_tsc_num_a702d6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['email'], name='students_te_email_84676f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['subjects_taught'], name='students_te_subject_f18e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_active'], name='students_te_is_acti_47a695_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_user_teacher'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
    ]
