# Generated by Django 6.0.4 on 2026-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_delete_classroom_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
