# Generated by Codex on 2026-06-07

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_rows_to_default_school(apps, schema_editor):
    School = apps.get_model('students', 'School')
    school = School.objects.order_by('id').first()
    if school is None:
        school = School.objects.create(
            name='Default School',
            code='default',
            tier='Basic',
            status='trial',
        )

    for model_name in [
        'Guardian',
        'Student',
        'Mark',
        'Teacher',
        'SubjectAssignment',
        'MarkSubmission',
        'ClassTeacherMasterComment',
        'Exam',
        'AssessmentLock',
    ]:
        Model = apps.get_model('students', model_name)
        Model.objects.filter(school__isnull=True).update(school=school)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_schoolprofile'),
    ]

    operations = [
        migrations.RenameModel(old_name='SchoolClient', new_name='School'),
        migrations.RenameField(model_name='school', old_name='schema_name', new_name='code'),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.SlugField(
                db_index=True,
                help_text='Used in logins, e.g. 0712345678@baringohigh',
                max_length=50,
                unique=True,
            ),
        ),
        migrations.DeleteModel(name='SchoolDomain'),
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=models.CharField(help_text='Unique phone number for SMS alerts', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tsc_number',
            field=models.CharField(
                help_text='Teacher Service Commission registration number',
                max_length=20,
                verbose_name='TSC Number',
            ),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(help_text="Teacher's email address", max_length=254),
        ),
        migrations.AddField(
            model_name='guardian',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardian_records', to='students.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_records', to='students.school'),
        ),
        migrations.AddField(
            model_name='mark',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mark_records', to='students.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_records', to='students.school'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjectassignment_records', to='students.school'),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marksubmission_records', to='students.school'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classteachermastercomment_records', to='students.school'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_records', to='students.school'),
        ),
        migrations.AddField(
            model_name='assessmentlock',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessmentlock_records', to='students.school'),
        ),
        migrations.RunPython(assign_existing_rows_to_default_school, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(name='guardian', unique_together={('school', 'phone')}),
        migrations.AlterUniqueTogether(name='student', unique_together={('school', 'admission_no')}),
        migrations.AlterUniqueTogether(name='subjectassignment', unique_together={('school', 'subject_code', 'class_name', 'stream')}),
        migrations.AlterUniqueTogether(name='marksubmission', unique_together={('school', 'teacher', 'subject_code', 'class_name', 'stream', 'exam_name', 'term', 'year')}),
        migrations.AlterUniqueTogether(name='classteachermastercomment', unique_together={('school', 'year', 'term', 'grade', 'stream', 'exam_type')}),
        migrations.AlterUniqueTogether(name='exam', unique_together={('school', 'name', 'term', 'year')}),
        migrations.AlterUniqueTogether(name='assessmentlock', unique_together={('school', 'year', 'term', 'exam_type', 'grade')}),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('school', 'tsc_number'), name='unique_school_teacher_tsc'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('school', 'phone_number'), name='unique_school_teacher_phone'),
        ),
    ]
