# Generated by Django 6.0.4 on 2026-06-07 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_shared_school_architecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_tsc_num_a702d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_email_84676f_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_subject_f18e5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='students_te_is_acti_47a695_idx',
        ),
        migrations.AlterField(
            model_name='assessmentlock',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AlterField(
            model_name='marksubmission',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'tsc_number'], name='students_te_school__231432_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'email'], name='students_te_school__3d7583_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'subjects_taught'], name='students_te_school__a70cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'is_active'], name='students_te_school__580585_idx'),
        ),
    ]
