# Generated by Django 6.0.4 on 2026-06-08 18:50

import django.db.models.deletion
import students.security.encryption
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_delete_schoolprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='integrity_checksum',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional parent portal account (read-only access to linked learners).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mark',
            name='integrity_checksum',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional student portal account (read-only access to own records).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='national_id',
            field=students.security.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_id_snapshot', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, max_length=10)),
                ('target_model', models.CharField(db_index=True, max_length=120)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('target_fields', models.JSONField(blank=True, default=list)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('school_id_snapshot', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('record_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='students_se_target__727025_idx'), models.Index(fields=['school_id_snapshot', 'timestamp'], name='students_se_school__2c7a69_idx')],
            },
        ),
    ]
