# Generated by Django 6.0.4 on 2026-06-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_add_gender_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='national_id',
        ),
    ]
