# Generated by Django 6.0.4 on 2026-06-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_remove_guardian_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteachermastercomment',
            name='ht_comment_ae1',
            field=models.TextField(blank=True, default='Approaching competence. Increased focus on weak subjects is required.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='ht_comment_ae2',
            field=models.TextField(blank=True, default='Developing competence. Closer monitoring and regular remedial work needed.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='ht_comment_be1',
            field=models.TextField(blank=True, default='Emerging competence. Needs intensive academic intervention and tracking.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='ht_comment_be2',
            field=models.TextField(blank=True, default='Critical support required. Immediate parental and teacher guidance needed.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='ht_comment_ee1',
            field=models.TextField(blank=True, default='An exceptional performance. Maintain this brilliant standard.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='ht_comment_ee2',
            field=models.TextField(blank=True, default='A very good performance. Keep up the high level of effort.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='ht_comment_me1',
            field=models.TextField(blank=True, default='A solid and commendable performance across most subjects.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='ht_comment_me2',
            field=models.TextField(blank=True, default='A fair performance. With more consistency, a better grade is attainable.'),
        ),
    ]
