# Generated by Django 6.0.4 on 2026-06-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_add_headteacher_plv_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHeadteacherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('term', models.CharField(max_length=20)),
                ('exam_type', models.CharField(max_length=50)),
                ('ht_comment_ee1', models.TextField(blank=True, default='An exceptional performance. Maintain this brilliant standard.')),
                ('ht_comment_ee2', models.TextField(blank=True, default='A very good performance. Keep up the high level of effort.')),
                ('ht_comment_me1', models.TextField(blank=True, default='A solid and commendable performance across most subjects.')),
                ('ht_comment_me2', models.TextField(blank=True, default='A fair performance. With more consistency, a better grade is attainable.')),
                ('ht_comment_ae1', models.TextField(blank=True, default='Approaching competence. Increased focus on weak subjects is required.')),
                ('ht_comment_ae2', models.TextField(blank=True, default='Developing competence. Closer monitoring and regular remedial work needed.')),
                ('ht_comment_be1', models.TextField(blank=True, default='Emerging competence. Needs intensive academic intervention and tracking.')),
                ('ht_comment_be2', models.TextField(blank=True, default='Critical support required. Immediate parental and teacher guidance needed.')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school')),
            ],
            options={
                'unique_together': {('school', 'year', 'term', 'exam_type')},
            },
        ),
    ]
