# Generated by Django 6.0.4 on 2026-06-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_schoolheadteachercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Force teacher to change password on first login'),
        ),
    ]
