# Generated by Django 6.0.4 on 2026-06-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_add_must_change_password_to_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentlock',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this lock applies to', max_length=10),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this comment applies to', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this exam belongs to', max_length=10),
        ),
        migrations.AddField(
            model_name='grade',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this grade belongs to', max_length=10),
        ),
        migrations.AddField(
            model_name='mark',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this mark belongs to', max_length=10),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this submission belongs to', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolheadteachercomment',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this comment applies to', max_length=10),
        ),
        migrations.AddField(
            model_name='stream',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this stream belongs to', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this student belongs to', max_length=10),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this assignment belongs to', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary'), ('BOTH', 'Both Sections')], default='BOTH', help_text='Which section this teacher belongs to', max_length=10),
        ),
        migrations.AlterField(
            model_name='assessmentlock',
            name='grade',
            field=models.CharField(choices=[('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='class_name',
            field=models.CharField(choices=[('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
    ]
