# Generated by Django 6.0.4 on 2026-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_add_school_section_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='primary_descriptor',
            field=models.CharField(blank=True, choices=[('EE', 'Exceeding Expectations'), ('ME', 'Meeting Expectations'), ('AE', 'Approaching Expectations'), ('BE', 'Below Expectations'), ('AB', 'Absent')], default='', help_text='CBC competency descriptor: EE, ME, AE, BE, or AB', max_length=2),
        ),
        migrations.AddField(
            model_name='mark',
            name='primary_performance_point',
            field=models.CharField(blank=True, default='', help_text="Primary rank scale: 1, 2, 3, 4 or 'AB' if absent", max_length=10),
        ),
        migrations.AddField(
            model_name='mark',
            name='primary_raw_score',
            field=models.CharField(blank=True, default='', help_text="Primary raw score: whole number (e.g. 85) or 'AB' if absent", max_length=10),
        ),
    ]
