# Generated by Django 6.0.4 on 2026-06-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_add_primary_assessment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique subject code, e.g. ENG, MAT', max_length=10)),
                ('name', models.CharField(help_text='Official subject / learning area name', max_length=100)),
                ('school_section', models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], help_text='Which section this subject belongs to', max_length=10)),
                ('grade', models.CharField(choices=[('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], help_text='Grade level this subject is offered at', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['school_section', 'grade', 'code'],
                'unique_together': {('school', 'code', 'school_section', 'grade')},
            },
        ),
    ]
