# Generated by Django 6.0.4 on 2026-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_add_subject_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='school_section',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], default='JSS', help_text='Which section this guardian belongs to', max_length=10),
        ),
    ]
