# Generated by Django 6.0.4 on 2026-06-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0046_add_school_section_to_guardian'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentlock',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assessmentlock',
            name='exam_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentlock',
            unique_together={('school', 'year', 'term', 'exam_type', 'grade', 'school_section')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'name', 'term', 'year', 'school_section')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolheadteachercomment',
            unique_together={('school', 'year', 'term', 'exam_type', 'school_section')},
        ),
    ]
