# Generated by Django 6.0.4 on 2026-06-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_add_school_section_to_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marksubmission',
            unique_together={('school', 'teacher', 'subject_code', 'class_name', 'stream', 'exam_name', 'term', 'year', 'school_section')},
        ),
    ]
