# Generated by Django 6.0.4 on 2026-06-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0048_add_school_section_to_marksubmission_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolheadteachercomment',
            name='ht_comment_ae',
            field=models.TextField(blank=True, default='Satisfactory performance. More focus on weak areas is needed.'),
        ),
        migrations.AddField(
            model_name='schoolheadteachercomment',
            name='ht_comment_be',
            field=models.TextField(blank=True, default='Needs improvement. Intensive support and parental guidance required.'),
        ),
        migrations.AddField(
            model_name='schoolheadteachercomment',
            name='ht_comment_ee',
            field=models.TextField(blank=True, default='Excellent performance. Maintain this brilliant standard.'),
        ),
        migrations.AddField(
            model_name='schoolheadteachercomment',
            name='ht_comment_me',
            field=models.TextField(blank=True, default='Good performance. Keep up the effort and aim higher.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='stream',
            field=models.CharField(max_length=20),
        ),
    ]
