# Generated by Django 6.0.4 on 2026-06-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0049_add_primary_headteacher_comment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteachermastercomment',
            name='comment_ae',
            field=models.TextField(blank=True, default='Satisfactory performance. More focus on weak areas is needed.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='comment_be',
            field=models.TextField(blank=True, default='Needs improvement. Intensive support and parental guidance required.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='comment_ee',
            field=models.TextField(blank=True, default='Excellent performance. Maintain this brilliant standard.'),
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='comment_me',
            field=models.TextField(blank=True, default='Good performance. Keep up the effort and aim higher.'),
        ),
    ]
