# Generated by Django 6.0.4 on 2026-06-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0050_add_primary_class_teacher_comment_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteachermastercomment',
            name='headteacher_comment',
        ),
        migrations.RemoveField(
            model_name='classteachermastercomment',
            name='ht_comment_ae1',
        ),
        migrations.RemoveField(
            model_name='classteachermastercomment',
            name='ht_comment_ae2',
        ),
        migrations.RemoveField(
            model_name='classteachermastercomment',
            name='ht_comment_be1',
        ),
        migrations.RemoveField(
            model_name='classteachermastercomment',
            name='ht_comment_be2',
        ),
        migrations.RemoveField(
            model_name='classteachermastercomment',
            name='ht_comment_ee1',
        ),
        migrations.RemoveField(
            model_name='classteachermastercomment',
            name='ht_comment_ee2',
        ),
        migrations.RemoveField(
            model_name='classteachermastercomment',
            name='ht_comment_me1',
        ),
        migrations.RemoveField(
            model_name='classteachermastercomment',
            name='ht_comment_me2',
        ),
        migrations.AddField(
            model_name='classteachermastercomment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='frozen_class_teacher_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mark',
            name='frozen_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='frozen_headteacher_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mark',
            name='frozen_opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolheadteachercomment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_ae',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_ae1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_ae2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_be',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_be1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_be2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_ee',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_ee1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_ee2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_me',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_me1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classteachermastercomment',
            name='comment_me2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_ae',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_ae1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_ae2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_be',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_be1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_be2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_ee',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_ee1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_ee2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_me',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_me1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolheadteachercomment',
            name='ht_comment_me2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
