# Generated by Django 6.0.4 on 2026-06-15 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0051_comment_freeze_and_blank_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='subject_fk',
            field=models.ForeignKey(blank=True, help_text='Subject for this mark', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='students.subject'),
        ),
        migrations.AddField(
            model_name='marksubmission',
            name='subject_fk',
            field=models.ForeignKey(blank=True, help_text='Subject for this submission', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='students.subject'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='subject_fk',
            field=models.ForeignKey(blank=True, help_text='Subject assigned to this teacher', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='students.subject'),
        ),
    ]
