# Generated by Django 6.0.4 on 2026-06-15 11:15

from django.db import migrations


# Maps subject codes to (name, school_section)
SUBJECT_INFO = {
    # Primary
    'ENG': ('English', 'PRIMARY'),
    'KIS': ('Kiswahili', 'PRIMARY'),
    'MAT': ('Mathematics', 'PRIMARY'),
    'SCI': ('Science and Technology', 'PRIMARY'),
    'SOC': ('Social Studies', 'PRIMARY'),
    'CRE': ('Christian Religious Education', 'PRIMARY'),
    'IRE': ('Islamic Religious Education', 'PRIMARY'),
    'AGR': ('Agriculture and Nutrition', 'PRIMARY'),
    'CAS': ('Creative Arts and Sports', 'PRIMARY'),
    # JSS
    '901': ('English Language', 'JSS'),
    '902': ('Kiswahili', 'JSS'),
    '903': ('Mathematics', 'JSS'),
    '904': ('Kenyan Sign Language', 'JSS'),
    '905': ('Integrated Science', 'JSS'),
    '906': ('Agriculture and Nutrition', 'JSS'),
    '907': ('Social Studies', 'JSS'),
    '908': ('CRE', 'JSS'),
    '909': ('IRE', 'JSS'),
    '910': ('HRE', 'JSS'),
    '911': ('Creative Arts and Sports', 'JSS'),
    '912': ('Pre-Technical Studies', 'JSS'),
}


def get_grade_for_mark(mark, school_section):
    """Determine grade from student's class_name."""
    return mark.student.class_name


def get_grade_for_assignment(assignment, school_section):
    """Grade is the class_name of the assignment."""
    return assignment.class_name


def get_grade_for_submission(submission, school_section):
    """Grade is the class_name of the submission."""
    return submission.class_name


def populate_subject_fks(apps, schema_editor):
    Subject = apps.get_model('students', 'Subject')
    Mark = apps.get_model('students', 'Mark')
    SubjectAssignment = apps.get_model('students', 'SubjectAssignment')
    MarkSubmission = apps.get_model('students', 'MarkSubmission')

    db_alias = schema_editor.connection.alias

    # Cache subjects by (school_id, code, school_section, grade)
    subject_cache = {}

    def get_or_create_subject(school_id, code, school_section, grade):
        key = (school_id, code, school_section, grade)
        if key in subject_cache:
            return subject_cache[key]

        name, default_section = SUBJECT_INFO.get(code, (code, school_section))
        subject, created = Subject.objects.using(db_alias).get_or_create(
            school_id=school_id,
            code=code,
            school_section=school_section,
            grade=grade,
            defaults={'name': name, 'is_active': True}
        )
        subject_cache[key] = subject
        return subject

    # --- Populate Mark.subject_fk ---
    for mark in Mark.objects.using(db_alias).filter(subject_fk__isnull=True).iterator():
        code = mark.subject  # Old CharField value
        if not code:
            continue
        school_section = mark.school_section
        grade = get_grade_for_mark(mark, school_section)
        subject = get_or_create_subject(mark.school_id, code, school_section, grade)
        mark.subject_fk = subject
        mark.save(update_fields=['subject_fk'])

    # --- Populate SubjectAssignment.subject_fk ---
    for assignment in SubjectAssignment.objects.using(db_alias).filter(subject_fk__isnull=True).iterator():
        code = assignment.subject_code  # Old CharField value
        if not code:
            continue
        school_section = assignment.school_section
        grade = get_grade_for_assignment(assignment, school_section)
        subject = get_or_create_subject(assignment.school_id, code, school_section, grade)
        assignment.subject_fk = subject
        assignment.save(update_fields=['subject_fk'])

    # --- Populate MarkSubmission.subject_fk ---
    for submission in MarkSubmission.objects.using(db_alias).filter(subject_fk__isnull=True).iterator():
        code = submission.subject_code  # Old CharField value
        if not code:
            continue
        school_section = submission.school_section
        grade = get_grade_for_submission(submission, school_section)
        subject = get_or_create_subject(submission.school_id, code, school_section, grade)
        submission.subject_fk = subject
        submission.save(update_fields=['subject_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_add_subject_fks'),
    ]

    operations = [
        migrations.RunPython(populate_subject_fks, migrations.RunPython.noop),
    ]