# Generated by Django 6.0.4 on 2026-06-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0053_populate_subject_fks'),
    ]

    operations = [
        # First, update unique_together constraints using raw SQL (before removing old fields)
        migrations.RunSQL(
            sql=[
                # SubjectAssignment: Add new unique constraint on subject FK
                'ALTER TABLE "students_subjectassignment" ADD CONSTRAINT "students_subjectassignment_school_subject_class_name_stre_uniq" UNIQUE ("school_id", "subject_fk_id", "class_name", "stream");',
                # MarkSubmission: Add new unique constraint on subject FK
                'ALTER TABLE "students_marksubmission" ADD CONSTRAINT "students_marksubmission_school_teacher_subject_class_name__uniq" UNIQUE ("school_id", "teacher_id", "subject_fk_id", "class_name", "stream", "exam_name", "term", "year", "school_section");',
            ],
            reverse_sql=[
                'ALTER TABLE "students_subjectassignment" DROP CONSTRAINT IF EXISTS "students_subjectassignment_school_subject_class_name_stre_uniq";',
                'ALTER TABLE "students_marksubmission" DROP CONSTRAINT IF EXISTS "students_marksubmission_school_teacher_subject_class_name__uniq";',
            ],
        ),
        # Drop old unique constraints
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "students_subjectassignment" DROP CONSTRAINT IF EXISTS "students_subjectassignment_school_subject_code_class_name_s_uniq";',
                'ALTER TABLE "students_marksubmission" DROP CONSTRAINT IF EXISTS "students_marksubmission_school_teacher_subject_code_class_nam_uniq";',
            ],
            reverse_sql=[
                'ALTER TABLE "students_subjectassignment" ADD CONSTRAINT "students_subjectassignment_school_subject_code_class_name_s_uniq" UNIQUE ("school_id", "subject_code", "class_name", "stream");',
                'ALTER TABLE "students_marksubmission" ADD CONSTRAINT "students_marksubmission_school_teacher_subject_code_class_nam_uniq" UNIQUE ("school_id", "teacher_id", "subject_code", "class_name", "stream", "exam_name", "term", "year", "school_section");',
            ],
        ),
        # Now remove old fields and rename FK fields
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='subject_fk',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='subject_code',
        ),
        migrations.RenameField(
            model_name='subjectassignment',
            old_name='subject_fk',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='marksubmission',
            name='subject_code',
        ),
        migrations.RenameField(
            model_name='marksubmission',
            old_name='subject_fk',
            new_name='subject',
        ),
    ]