# Generated by Django 6.0.4 on 2026-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0059_add_notification_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assessmentlock',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_report_mode',
            field=models.CharField(choices=[('UNMERGED', 'Unmerged (Individual Subjects)'), ('INTEGRATED_KNEC', 'Integrated KNEC (Merged Papers)')], default='UNMERGED', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], help_text='Grade level this subject is offered at', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school_section',
            field=models.CharField(choices=[('LOWER_PRIMARY', 'Lower Primary'), ('PRIMARY', 'Primary'), ('JSS', 'Junior Secondary')], help_text='Which section this subject belongs to', max_length=15),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='class_name',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='component_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='component_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='merge_group_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='merge_group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='sub_section',
            field=models.CharField(choices=[('LOWER', 'Lower Primary'), ('UPPER', 'Upper Primary')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='marksubmission',
            unique_together={('school', 'teacher', 'subject', 'class_name', 'stream', 'exam_name', 'term', 'year', 'school_section')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('school', 'subject', 'class_name', 'stream')},
        ),
    ]
