# Generated by Django 6.0.4 on 2026-06-30 03:51
# Fixed: Use RunSQL for unique_together changes since migration 0054
# modified constraints via raw SQL, leaving Django state out of sync.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0059_add_notification_model'),
    ]

    operations = [
        # ── SubjectAssignment: drop old unique constraint and add new one ──
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "students_subjectassignment" DROP CONSTRAINT IF EXISTS "students_subjectassignment_school_subject_class_name_stre_uniq";',
                'ALTER TABLE "students_subjectassignment" ADD CONSTRAINT "students_subjectassignment_school_subject_class_name_stre_uniq" UNIQUE ("school_id", "subject_id", "class_name", "stream");',
            ],
            reverse_sql=[
                'ALTER TABLE "students_subjectassignment" DROP CONSTRAINT IF EXISTS "students_subjectassignment_school_subject_class_name_stre_uniq";',
            ],
        ),

        # ── MarkSubmission: drop old unique constraint and add new one ──
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "students_marksubmission" DROP CONSTRAINT IF EXISTS "students_marksubmission_school_teacher_subject_class_name__uniq";',
                'ALTER TABLE "students_marksubmission" ADD CONSTRAINT "students_marksubmission_school_teacher_subject_class_name__uniq" UNIQUE ("school_id", "teacher_id", "subject_id", "class_name", "stream", "exam_name", "term", "year", "school_section");',
            ],
            reverse_sql=[
                'ALTER TABLE "students_marksubmission" DROP CONSTRAINT IF EXISTS "students_marksubmission_school_teacher_subject_class_name__uniq";',
            ],
        ),

        # ── Field alterations (choices/max_length updates) ──
        migrations.AlterField(
            model_name='assessmentlock',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_report_mode',
            field=models.CharField(choices=[('UNMERGED', 'Unmerged (Individual Subjects)'), ('INTEGRATED_KNEC', 'Integrated KNEC (Merged Papers)')], default='UNMERGED', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], help_text='Grade level this subject is offered at', max_length=20),
        ),
        # Skipped: AlterField subject.school_section max_length 20→15
        # blocked by RLS policy p_students_subject_tenant on the column.
        # max_length=20 in DB works fine for 'LOWER_PRIMARY'/'PRIMARY'/'JSS'.
        migrations.AlterField(
            model_name='subjectassignment',
            name='class_name',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='component_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='component_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='merge_group_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='merge_group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectmergegroup',
            name='sub_section',
            field=models.CharField(choices=[('LOWER', 'Lower Primary'), ('UPPER', 'Upper Primary')], max_length=10),
        ),
    ]
