# Generated by Django 6.0.4 on 2026-06-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0060_alter_subjectassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectassignment',
            name='sub_section',
            field=models.CharField(blank=True, choices=[('LOWER', 'Lower Primary'), ('UPPER', 'Upper Primary')], help_text='Lower Primary (1-3) or Upper Primary (4-6). NULL for JSS.', max_length=10, null=True),
        ),
    ]
