# Generated by Django 6.0.4 on 2026-07-03 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0062_alter_subject_school_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_section', models.CharField(choices=[('LOWER_PRIMARY', 'Lower Primary (Grades 1-3)'), ('PRIMARY', 'Primary (Grades 4-6)'), ('JSS', 'Junior Secondary (Grades 7-9)')], max_length=20)),
                ('subject_scale', models.JSONField(blank=True, default=list, help_text='Mark ranges for individual subject performance levels')),
                ('total_scale', models.JSONField(blank=True, default=list, help_text='Mark ranges for overall/aggregated performance levels')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school')),
            ],
            options={
                'verbose_name': 'Grading Configuration',
                'verbose_name_plural': 'Grading Configurations',
                'unique_together': {('school', 'school_section')},
            },
        ),
    ]
