# Generated by Django 6.0.4 on 2026-07-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0063_gradingconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentlock',
            unique_together={('school', 'year', 'term', 'exam_type', 'grade', 'school_section', 'sub_section')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'name', 'term', 'year', 'school_section', 'sub_section')},
        ),
    ]
