# Generated by Django 6.0.4 on 2026-07-09 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0064_alter_assessmentlock_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='assessmentlock',
            unique_together={('school', 'year', 'term', 'exam_type', 'grade', 'school_section')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'name', 'term', 'year', 'school_section')},
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'subject', 'term', 'exam_type', 'year'], name='mark_sheet_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'student', 'subject', 'term', 'exam_type', 'year'], name='mark_student_idx'),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', '-created_at'], name='pwdhist_user_idx'),
        ),
    ]
