# Generated by Django 6.0.4 on 2026-07-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0065_passwordhistory_alter_assessmentlock_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mark',
            name='mark_sheet_idx',
        ),
        migrations.RemoveIndex(
            model_name='mark',
            name='mark_student_idx',
        ),
    ]
