# Generated by Django 6.0.4 on 2026-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0066_remove_mark_mark_sheet_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradingconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gradingconfig',
            name='sub_section',
            field=models.CharField(blank=True, choices=[('LOWER', 'Lower Primary (Grades 1-3)'), ('UPPER', 'Upper Primary (Grades 4-6)')], help_text='Lower or Upper primary. NULL for JSS or shared Primary scale.', max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gradingconfig',
            unique_together={('school', 'school_section', 'sub_section')},
        ),
    ]
