# Generated by Django 6.0.4 on 2026-07-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0067_grading_config_sub_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'name', 'term', 'year', 'school_section', 'sub_section')},
        ),
    ]
