# Generated by Django 6.0.4 on 2026-08-02 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0070_examsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsummary',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='students.school'),
        ),
        migrations.AlterField(
            model_name='examsummary',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='examsummary',
            index=models.Index(fields=['school', 'term', 'year', 'exam_name'], name='summary_exam_idx'),
        ),
        migrations.AddIndex(
            model_name='examsummary',
            index=models.Index(fields=['school', 'student', 'year'], name='summary_student_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'student', 'term', 'year', 'exam_type'], name='mark_student_exam_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'subject', 'term', 'year'], name='mark_subject_exam_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'term', 'year', 'exam_type'], name='mark_exam_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'school_section', 'term', 'year'], name='mark_section_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notification_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_name', 'stream'], name='student_class_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'school_section', 'class_name'], name='student_section_idx'),
        ),
    ]
