# Generated by Django 6.0.4 on 2026-08-03 20:24

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0071_add_composite_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_student_id', models.PositiveIntegerField(help_text='PK of the student before removal')),
                ('admission_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('gender', models.CharField(default='Not Specified', max_length=15)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=100)),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=20)),
                ('religion', models.CharField(blank=True, default='None', max_length=10)),
                ('assessment_no', models.CharField(blank=True, max_length=50, null=True)),
                ('school_section', models.CharField(default='JSS', max_length=10)),
                ('sub_section', models.CharField(blank=True, max_length=10, null=True)),
                ('term', models.CharField(default='Term 1', max_length=20)),
                ('year', models.IntegerField(default=students.models.current_year)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('removed_by', models.ForeignKey(help_text='Admin who removed this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_students', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_students', to='students.school')),
            ],
            options={
                'verbose_name': 'Removed Student',
                'verbose_name_plural': 'Removed Students',
                'ordering': ['-removed_at'],
                'indexes': [models.Index(fields=['school', '-removed_at'], name='removed_student_school_idx')],
            },
        ),
    ]
