# Generated by Django 6.0.4 on 2026-08-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0073_student_date_removed_student_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', help_text="Teacher's gender", max_length=10, verbose_name='Gender'),
        ),
    ]
