# Generated by Django 6.0.4 on 2026-08-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0074_add_gender_to_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Postal or physical address', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short biography or notes about the teacher', verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employee_number',
            field=models.CharField(blank=True, default='', help_text='Internal employee number', max_length=30, verbose_name='Employee Number'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='national_id',
            field=models.CharField(blank=True, default='', help_text='National identification number', max_length=30, verbose_name='National ID No.'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='signature',
            field=models.ImageField(blank=True, help_text="Teacher's digital signature image", null=True, upload_to='teacher_signatures/', verbose_name='Signature'),
        ),
    ]
