# Generated by Django 6.0.4 on 2026-08-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0075_add_teacher_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectassignment',
            name='teacher_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.teacher'),
        ),
    ]
