# Generated by Django 6.0.4 on 2026-08-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0076_make_teacher_profile_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradingconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gradingconfig',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Display name for this grading system', max_length=150),
        ),
    ]
