# Generated by Django 6.0.4 on 2026-08-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0077_add_gradingconfig_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Standard JSS Scale', 'KCSE Style'", max_length=100)),
                ('subject_scale', models.JSONField(blank=True, default=list, help_text='Mark ranges for individual subject performance levels')),
                ('total_scale', models.JSONField(blank=True, default=list, help_text='Mark ranges for overall/aggregated performance levels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='students.school')),
            ],
            options={
                'verbose_name': 'Grading Scale',
                'verbose_name_plural': 'Grading Scales',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_section', models.CharField(help_text="e.g. 'JSS', 'PRIMARY'", max_length=20)),
                ('sub_section', models.CharField(blank=True, help_text='LOWER or UPPER primary. NULL for JSS.', max_length=10, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_assignments', to='students.school')),
                ('subject', models.ForeignKey(blank=True, help_text='NULL = general fallback for section. Set = subject-specific.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_assignments', to='students.subject')),
                ('grading_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='students.gradingscale')),
            ],
            options={
                'verbose_name': 'Grading Assignment',
                'verbose_name_plural': 'Grading Assignments',
                'constraints': [models.UniqueConstraint(condition=models.Q(('subject__isnull', True)), fields=('school', 'school_section', 'sub_section'), name='uniq_general_scale_assignment'), models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('school', 'school_section', 'sub_section', 'subject'), name='uniq_subject_scale_assignment')],
            },
        ),
    ]
