# Generated by Django 6.0.4 on 2026-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0080_add_soft_delete_to_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, help_text='e.g., Excellence · Discipline · Character', max_length=255, null=True, verbose_name='School Motto'),
        ),
    ]
