# Generated by Django 6.0.4 on 2026-08-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0081_add_motto_to_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='other_names',
            field=models.CharField(blank=True, default='', help_text='Middle or other names', max_length=100, verbose_name='Other Names'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Teacher's profile photo", null=True, upload_to='teacher_profiles/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('CRE', 'CRE'), ('IRE', 'IRE'), ('HRE', 'HRE'), ('None', 'None')], default='None', max_length=10, null=True, verbose_name='Religious Education'),
        ),
    ]
