# Generated by Django 6.0.4 on 2026-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0082_add_teacher_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='boarding_status',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Boarding', 'Boarding'), ('Day & Boarding', 'Day & Boarding')], default='Day', max_length=20, verbose_name='Boarding Status'),
        ),
        migrations.AddField(
            model_name='school',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('Mixed School', 'Mixed School'), ('Boys School', 'Boys School'), ('Girls School', 'Girls School')], default='Mixed School', max_length=20, verbose_name='Gender Type'),
        ),
        migrations.AddField(
            model_name='school',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, help_text='e.g., CSS', max_length=50, null=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='school',
            name='vision',
            field=models.TextField(blank=True, null=True, verbose_name='Vision'),
        ),
    ]
