# Generated by Django 6.0.4 on 2026-08-19 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0083_add_school_settings_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(verbose_name='Academic Year')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10, verbose_name='Term')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_dates', to='students.school')),
            ],
            options={
                'verbose_name': 'Term Date',
                'verbose_name_plural': 'Term Dates',
                'ordering': ['-academic_year', 'term'],
                'unique_together': {('school', 'academic_year', 'term')},
            },
        ),
    ]
