# Generated by Django 6.0.4 on 2026-08-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0084_add_termdate_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='termdate',
            name='week_starts_on',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Sunday', 'Sunday')], default='Monday', max_length=10, verbose_name='Week Starts On'),
        ),
    ]
