# Generated by Django 6.0.4 on 2026-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0085_add_week_starts_on'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'student', 'subject', 'term', 'exam_type', 'year', 'school_section', 'sub_section'], name='mark_upsert_idx'),
        ),
    ]
