# Generated by Django 6.0.4 on 2026-09-05 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0086_add_mark_upsert_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, max_length=10)),
                ('term', models.CharField(blank=True, default='', max_length=20)),
                ('year', models.IntegerField(default=0)),
                ('exam_type', models.CharField(blank=True, default='', max_length=50)),
                ('old_raw_score', models.PositiveIntegerField(blank=True, null=True)),
                ('old_score', models.PositiveIntegerField(blank=True, null=True)),
                ('old_is_absent', models.BooleanField(blank=True, null=True)),
                ('new_raw_score', models.PositiveIntegerField(blank=True, null=True)),
                ('new_score', models.PositiveIntegerField(blank=True, null=True)),
                ('new_is_absent', models.BooleanField(blank=True, null=True)),
                ('new_performance_level', models.CharField(blank=True, default='', max_length=50)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('school', 'student', 'subject', 'term', 'exam_type', 'year', 'school_section', 'sub_section'), name='mark_unique_per_student_subject_exam'),
        ),
        migrations.AddField(
            model_name='markauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markauditlog',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.school'),
        ),
        migrations.AddField(
            model_name='markauditlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AddField(
            model_name='markauditlog',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject'),
        ),
        migrations.AddIndex(
            model_name='markauditlog',
            index=models.Index(fields=['school', 'student', 'timestamp'], name='mark_audit_student_idx'),
        ),
        migrations.AddIndex(
            model_name='markauditlog',
            index=models.Index(fields=['school', 'subject', 'timestamp'], name='mark_audit_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='markauditlog',
            index=models.Index(fields=['actor', 'timestamp'], name='mark_audit_actor_idx'),
        ),
    ]
