# Generated by Django 6.0.4 on 2026-09-08 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0087_markauditlog_mark_updated_at_mark_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('date_mode', models.CharField(choices=[('single', 'Single'), ('range', 'Range')], default='single', max_length=10, verbose_name='Date Mode')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Event Time')),
                ('participants', models.CharField(choices=[('Teachers', 'Teachers'), ('Parents', 'Parents'), ('All', 'All')], default='All', max_length=20, verbose_name='Participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='students.school')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_date', 'time'],
            },
        ),
    ]
