# Generated by Django 6.0.4 on 2026-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0088_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_stream',
            field=models.CharField(blank=True, help_text='Original stream before combine. Used to restore split.', max_length=20, null=True),
        ),
    ]
