# Generated by Django 6.0.4 on 2026-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0089_add_previous_stream_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectassignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False when archived after a stream combine/split. Only active assignments appear in mark entry.'),
        ),
    ]
