# Generated by Django 6.0.4 on 2026-09-10 16:19

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0090_add_is_active_to_subjectassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/', validators=[students.models.validate_image_size], verbose_name='Official School Logo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Teacher's profile photo", null=True, upload_to='teacher_profiles/', validators=[students.models.validate_image_size], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='signature',
            field=models.ImageField(blank=True, help_text="Teacher's digital signature image", null=True, upload_to='teacher_signatures/', validators=[students.models.validate_image_size], verbose_name='Signature'),
        ),
        migrations.AddIndex(
            model_name='classteachermastercomment',
            index=models.Index(fields=['school', 'year', 'term', 'grade', 'stream'], name='ctmc_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['student'], name='mark_student_idx'),
        ),
        migrations.AddIndex(
            model_name='marksubmission',
            index=models.Index(fields=['subject'], name='ms_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='marksubmission',
            index=models.Index(fields=['status'], name='ms_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['teacher_profile'], name='sa_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['is_active'], name='sa_active_idx'),
        ),
    ]
