# Generated by Django 6.0.4 on 2026-09-12 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0092_exam_result_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marksubmission',
            name='published_by',
            field=models.ForeignKey(blank=True, help_text='Admin who published these results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
