# Generated by Django 6.0.4 on 2026-09-13 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0094_exam_min_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'year', 'term'], name='exam_school_term_idx'),
        ),
        migrations.AddIndex(
            model_name='examresultsnapshot',
            index=models.Index(fields=['school', 'year', 'term', 'exam_name', 'class_name', 'stream'], name='snapshot_full_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='examsummary',
            index=models.Index(fields=['school', 'year', 'term', 'exam_name', 'total_marks'], name='summary_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='examsummary',
            index=models.Index(fields=['school', 'year', 'term', 'exam_name', 'school_section', 'sub_section'], name='summary_section_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'year', 'term', 'exam_type', 'student', 'subject'], name='mark_report_card_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'year', 'term', 'exam_type', 'subject', 'student'], name='mark_subject_roster_idx'),
        ),
        migrations.AddIndex(
            model_name='marksubmission',
            index=models.Index(fields=['status', 'school', 'class_name', 'stream', 'year', 'term', 'exam_name'], name='ms_published_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='marksubmission',
            index=models.Index(fields=['school', 'class_name', 'stream', 'year', 'term', 'exam_name', 'status'], name='ms_stream_status_idx'),
        ),
        migrations.AddIndex(
            model_name='marksubmission',
            index=models.Index(fields=['school', 'status', 'year', 'term'], name='ms_admin_overview_idx'),
        ),
    ]
