# Generated by Django 6.0.4 on 2026-09-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0096_mark_backup_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksubmission',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.teacher'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='teacher_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='students.teacher'),
        ),
    ]
