# Generated by Django 6.0.4 on 2026-09-21 04:17

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0098_close_exam_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentlock',
            name='year',
            field=models.IntegerField(default=students.models.current_year),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['school', 'subject', 'term', 'year', 'exam_type'], name='mark_subject_exam_type_idx'),
        ),
    ]
