# Generated by Django 6.0.4 on 2026-10-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0099_add_mark_subject_exam_type_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-year', '-term', 'name']},
        ),
    ]
